[package]
name = "gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.19" }
serde = { version = "1.0", features = ["derive"] }
tui = { version = "0.14", default-features = false, features = ['crossterm'] }
thiserror = "1.0"
anyhow = "1.0.66"
tokio = { version = "1.11.0", features = ["full"] }
