[package]
name = "db"
version = "0.1.0"
edition = "2021"
readme = "CARGO.md"
keywords = ["database", "graph-database", "key-value", "key-value-store", "kv-store"]
categories = ["database-implementations", "data-structures", "graph"]
description = "A scalable, distributed, collaborative graph database build by digital nomads"
homepage = "https://github.com/surrealdb/solomondb"
documentation = "https://docs.rs/solomondb/"
repository = "https://github.com/surrealdb/solomondb"
license = "Apache-2.0"

[features]
default = ["kv-rocksdb"]
kv-rocksdb = ["dep:rocksdb"]

[dependencies]
rocksdb = {version ="0.19.0", optional=true}
thiserror = "1.0.37"

[dev-dependencies]
tokio = { version = "1.21.2", features = ["macros", "rt"] }