name: Main
on: [push, pull_request]

permissions:
  contents: read # for checkout
  pull-requests: write # for comments

jobs:
  build_and_lint:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    name: Test `cargo check/test` on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true
      - name: Build project
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --workspace --release --all-features
      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace
